name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd motoverse/ui
          npm install

      - name: Build
        run: |
          cd motoverse/ui
          npm run build -- --configuration production

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: motoverse/ui/docs
          branch: gh-pages 